feat(exit): add system register read and write exit reasons
arceos-hypervisor/axvcpu pull request #20
Opened 2024-11-26 07:30 UTC by luodeb

- Add SysRegRead and SysRegWrite variants to the AxVCpuExitReason enum
- SysRegRead contains address and register number for system register reads
- SysRegWrite contains address, register number, and data for system register writes

2024-11-26 14:29 UTC, aarkegz requested changes

2024-11-26 14:29 UTC, aarkegz commented on src/exit.rs
> +        addr: usize,
The name `addr` is kind of confusing. It's not a memory addr.

2024-11-26 14:29 UTC, aarkegz commented on src/exit.rs
> +        reg: usize,
This is **NOT** the number of the system register, according to your code in `arm_vcpu`, it's the number of the GPR.

2024-11-26 14:29 UTC, aarkegz commented on src/exit.rs
> +        reg: usize,
Do we need both `reg` and `value` here?

2024-11-27 02:12 UTC, luodeb commented on src/exit.rs
> +        reg: usize,
It seems like it's indeed a repetition.

2024-11-27 06:17 UTC, luodeb commented on src/exit.rs
> +        addr: usize,
ok

2024-11-27 06:17 UTC, luodeb commented on src/exit.rs
> +        reg: usize,
ok

2024-11-27 06:25 UTC, aarkegz approved these changes
LGTM

2024-11-27 06:26 UTC, merged