feat: add ci
arceos-hypervisor/axvcpu pull request #5
Opened 2024-08-01 07:07 UTC by hky1999

2024-08-01 07:11 UTC, aarkegz commented
This pr needs a better name.

2024-08-01 07:24 UTC, aarkegz requested changes

2024-08-01 07:24 UTC, aarkegz commented on .github/workflows/ci.yml
> +        targets: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat]
Maybe move `x86_64-unknown-linux-gnu` to a new `job`? It's only required for unit tests.

2024-08-02 02:29 UTC, hky1999 commented on .github/workflows/ci.yml
> +        targets: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat]
It's copied from [arceos-crates/templates](https://github.com/arceos-org/arceos-crates/tree/main/templates).

2024-08-02 05:29 UTC, hky1999 commented on .github/workflows/ci.yml
> +        targets: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat]
Considering this is an OS-independent crate, this `x86_64-unknown-linux-gnu` target is to make the checks for the crate more general? @equation314

2024-08-02 05:40 UTC, equation314 commented on .github/workflows/ci.yml
> +        targets: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat]
To build and run on host Linux (for cargo clippy & cargo test).

2024-08-02 05:44 UTC, equation314 commented on .github/workflows/ci.yml
> +        targets: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat]
In `arceos-crates`, some crates may have special considerations for `target_os = "linux"`.

2024-08-02 08:26 UTC, aarkegz commented on .github/workflows/ci.yml
> +        targets: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat]
OK

2024-08-02 08:48 UTC, hky1999 commented on .github/workflows/ci.yml
> +        targets: [x86_64-unknown-linux-gnu, x86_64-unknown-none, riscv64gc-unknown-none-elf, aarch64-unknown-none-softfloat]
> OK

need ning's approvement

2024-08-02 08:48 UTC, aarkegz approved these changes

2024-08-02 08:51 UTC, merged